---

version: '3'

services:

  postgres:
    image: 'postgres:9.6'
    network_mode: 'host'
    environment:
      POSTGRES_USER: 'atmosphere_db_user'
      POSTGRES_PASSWORD: 'atmosphere_db_pass'

  sut:
    build: .
    entrypoint: '/root/test.sh'
    network_mode: 'host'
    depends_on:
      - 'postgres'
