# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 21:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'delete_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='user_customizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
